const { app, BrowserWindow, ipcMain, dialog, shell, protocol, net } = require('electron')
const fs = require('node:fs'), fsp = fs.promises, path = require('node:path'), crypto = require('node:crypto')
const DEFAULT_EXCLUDES = ['node_modules', '.git', 'dist', 'build', '.cache', 'cache', 'caches', 'tmp', 'temp', 'archive', 'archives']
let win, db, dbFile, thumbnailDir, scanTimer, saveChain = Promise.resolve(), workers = 0
const queue = [], hash = value => crypto.createHash('sha256').update(value).digest('hex'), normalize = value => value.replaceAll('\\', '/')
async function loadDb() { dbFile = path.join(app.getPath('userData'), 'library.json'); thumbnailDir = path.join(app.getPath('userData'), 'thumbnails'); await fsp.mkdir(thumbnailDir, { recursive: true }); try { db = JSON.parse(await fsp.readFile(dbFile, 'utf8')) } catch { db = { version: 1, sources: [], files: [], preferences: { thumbnailSize: 1, launchAtLogin: false } } }; db.sources ||= []; db.files ||= []; db.preferences ||= {} }
function saveDb() { const data = JSON.stringify(db, null, 2), temp = `${dbFile}.tmp`; return saveChain = saveChain.then(async () => { await fsp.writeFile(temp, data); await fsp.rename(temp, dbFile) }) }
function state() { return { sources: db.sources, files: db.files.map(x => ({ ...x, thumbnailUrl: x.thumbnailPath ? `app-thumb://${encodeURIComponent(x.thumbnailPath)}` : null })), preferences: db.preferences } }
function notify() { if (win && !win.isDestroyed()) win.webContents.send('library-changed', state()) }
function excluded(relative, source) { const parts = normalize(relative).toLowerCase().split('/'); return [...DEFAULT_EXCLUDES, ...(source.exclusions || [])].map(x => x.toLowerCase().replace(/^\*\*\//, '').replace(/\/\*\*$/, '')).some(x => parts.includes(x)) }
async function walk(folder, source, result = []) { let entries; try { entries = await fsp.readdir(folder, { withFileTypes: true }) } catch { return result } for (const entry of entries) { const absolute = path.join(folder, entry.name), relative = path.relative(source.path, absolute); if (excluded(relative, source)) continue; if (entry.isDirectory() && source.includeSubfolders) await walk(absolute, source, result); else if (entry.isFile() && /\.html?$/i.test(entry.name)) result.push(absolute) } return result }
function metadata(html) { return { title: (html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim(), searchableText: html.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&\w+;/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 500000) } }
function queueThumbnail(item) { if (!queue.includes(item.id)) queue.push(item.id); pump() }
async function pump() { while (workers < 2 && queue.length) { const item = db.files.find(x => x.id === queue.shift()); if (!item || item.missing) continue; workers++; (async () => { const target = path.join(thumbnailDir, `${item.id}-${item.sha256.slice(0, 12)}.png`); try { await fsp.access(target) } catch { const thumbnailWindow = new BrowserWindow({ show: false, width: 1280, height: 900, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, javascript: false } }); try { await thumbnailWindow.loadFile(item.absolutePath); await new Promise(r => setTimeout(r, 350)); await fsp.writeFile(target, (await thumbnailWindow.webContents.capturePage()).toPNG()) } catch { item.broken = true } finally { thumbnailWindow.destroy() } } item.thumbnailPath = target; await saveDb(); notify() })().finally(() => { workers--; pump() }) } }
async function scan(sourceId) { const source = db.sources.find(x => x.id === sourceId); if (!source || !source.enabled) return; const paths = await walk(source.path, source), seen = new Set(paths.map(normalize)), now = Date.now(); for (const absolute of paths) try { const stat = await fsp.stat(absolute), key = normalize(absolute); let item = db.files.find(x => x.pathKey === key); if (!item) { item = { id: hash(key), sourceId, absolutePath: absolute, pathKey: key, relativePath: normalize(path.relative(source.path, absolute)), name: path.basename(absolute), discoveredAt: now, favorite: false, category: '', lastViewedAt: null }; db.files.push(item) } if (item.modifiedAt !== stat.mtimeMs || item.size !== stat.size || !item.sha256) { const content = await fsp.readFile(absolute); Object.assign(item, metadata(content.toString('utf8')), { size: stat.size, modifiedAt: stat.mtimeMs, sha256: hash(content), missing: false, changed: Boolean(item.lastViewedAt), broken: false }); queueThumbnail(item) } else item.missing = false } catch {} for (const item of db.files.filter(x => x.sourceId === sourceId)) item.missing = !seen.has(item.pathKey); Object.assign(source, { lastScan: now, fileCount: db.files.filter(x => x.sourceId === sourceId && !x.missing).length, missingFileCount: db.files.filter(x => x.sourceId === sourceId && x.missing).length }); await saveDb(); notify() }
function createWindow() { win = new BrowserWindow({ width: 1500, height: 950, minWidth: 900, minHeight: 600, show: false, backgroundColor: '#0c0d13', webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false, sandbox: true } }); win.removeMenu(); win.webContents.setWindowOpenHandler(() => ({ action: 'deny' })); win.once('ready-to-show', () => process.argv.includes('--minimized') ? win.minimize() : win.show()); app.isPackaged ? win.loadFile(path.join(__dirname, '..', 'dist', 'index.html')) : win.loadURL(process.env.VITE_DEV_SERVER_URL || 'http://localhost:3000') }
app.whenReady().then(async () => { await loadDb(); protocol.handle('app-thumb', req => net.fetch(`file://${decodeURIComponent(req.url.slice(12))}`)); createWindow(); db.sources.filter(x => x.enabled).forEach(x => scan(x.id)); scanTimer = setInterval(() => db.sources.filter(x => x.enabled).forEach(x => scan(x.id)), 5000) })
app.on('window-all-closed', () => { clearInterval(scanTimer); if (process.platform !== 'darwin') app.quit() })
ipcMain.handle('library:get', () => state())
ipcMain.handle('source:add', async () => { const answer = await dialog.showOpenDialog(win, { properties: ['openDirectory'] }); if (answer.canceled) return state(); const folder = answer.filePaths[0], sourceId = hash(normalize(folder)); if (!db.sources.some(x => x.id === sourceId)) db.sources.push({ id: sourceId, displayName: path.basename(folder), path: folder, includeSubfolders: true, includePatterns: ['**/*.html', '**/*.htm'], exclusions: [...DEFAULT_EXCLUDES], accent: '#817bf3', enabled: true, lastScan: null, fileCount: 0, missingFileCount: 0 }); await saveDb(); await scan(sourceId); return state() })
ipcMain.handle('source:update', async (_, patch) => { const source = db.sources.find(x => x.id === patch.id); if (source) Object.assign(source, patch, { id: source.id, path: source.path }); await saveDb(); return state() })
ipcMain.handle('scan', async (_, sourceId) => { for (const source of (sourceId ? db.sources.filter(x => x.id === sourceId) : db.sources)) await scan(source.id); return state() })
ipcMain.handle('file:open', (_, file) => shell.openPath(file.absolutePath)); ipcMain.handle('file:reveal', (_, file) => shell.showItemInFolder(file.absolutePath))
ipcMain.handle('file:viewed', async (_, fileId) => { const item = db.files.find(x => x.id === fileId); if (item) Object.assign(item, { lastViewedAt: Date.now(), changed: false }); await saveDb() })
ipcMain.handle('file:update', async (_, patch) => { const item = db.files.find(x => x.id === patch.id); if (item) Object.assign(item, { favorite: !!patch.favorite, category: String(patch.category || '') }); await saveDb(); return state() })
ipcMain.handle('preview:url', (_, fileId) => { const item = db.files.find(x => x.id === fileId); return item && !item.missing ? `file://${normalize(item.absolutePath)}` : null })
ipcMain.handle('registry:export', async () => { const answer = await dialog.showSaveDialog(win, { defaultPath: 'html-thumbnail-registry.json', filters: [{ name: 'JSON', extensions: ['json'] }] }); if (!answer.canceled) await fsp.writeFile(answer.filePath, JSON.stringify({ version: 1, sources: db.sources, metadata: db.files.map(({ pathKey, favorite, category, lastViewedAt }) => ({ pathKey, favorite, category, lastViewedAt })), preferences: db.preferences }, null, 2)); return !answer.canceled })
ipcMain.handle('registry:import', async () => { const answer = await dialog.showOpenDialog(win, { filters: [{ name: 'JSON', extensions: ['json'] }] }); if (answer.canceled) return state(); const data = JSON.parse(await fsp.readFile(answer.filePaths[0], 'utf8')); for (const source of data.sources || []) if (!db.sources.some(x => normalize(x.path) === normalize(source.path))) db.sources.push({ ...source, id: hash(normalize(source.path)) }); for (const meta of data.metadata || []) { const item = db.files.find(x => x.pathKey === meta.pathKey); if (item) Object.assign(item, meta, { id: item.id, pathKey: item.pathKey }) } await saveDb(); return state() })
ipcMain.handle('preference:set', async (_, { key, value }) => { db.preferences[key] = value; if (key === 'launchAtLogin') app.setLoginItemSettings({ openAtLogin: !!value, args: ['--minimized'] }); await saveDb(); return state() })
